name: Terraform plan

on:
  push:
    branches:
      - FeatureBranch

jobs:
  terraform:
    name: Terraform CI/CD
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: us-east-1  # Change if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::920372986500:role/github
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false
